version: '2'
services:
  ros-master:
    build: .
    hostname: ros-master
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore
    networks:
      - x11
      - my-network

  mobilesim:
    build: .
    depends_on:
      - novnc
    container_name: mobilesim
    hostname: mobilesim
    environment:
      - DISPLAY=novnc:0.0
    command:
      - MobileSim
    ports:
      - "8101:8101"
    networks:
      - x11
      - my-network
  
  ros-entrypoint:
    build: .
    container_name: ros-entrypoint
    volumes:
      - "./robot-client:/catkin_ws/src/robot-client:rw"
    environment:
      - ROS_HOSTNAME=ros-entrypoint
      - ROS_MASTER_URI=http://ros-master:11311
      - DISPLAY=novnc:0.0
    depends_on:
      - ros-master 
      - novnc
    command:
      - xterm
    networks:
      - x11
      - my-network

  novnc:  
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    ports:
      - "8080:8080"
    networks:
      - x11

networks:
  x11:
  my-network:
    driver: bridge
